alias gitgraph="git log --graph --all --pretty=format:'%C(yellow) %h  %C(reset)%C(blue)%ad%C(reset) : %C(white)%s %C(bold green)-- %an%C(reset) %C(bold red)%d%C(reset)' --date=relative"
alias gs="git status"
alias gg="gitgraph"
alias vi="nvim"
alias pserve="python3 -m http.server"
