export USER="bena"
export MAIL="bena@student.42seoul.kr"
alias norm="norminette -R CheckForbiddenSourceHeader"
alias normh="norminette -R CheckDefine"
alias normall="norm */*.c;normh */*.h"
alias gccw="gcc -Wall -Wextra -Werror"
alias rc="clear; printf '\e[3J'"
alias gitgraph="git log --graph --all --pretty=format:'%C(yellow) %h  %C(reset)%C(blue)%ad%C(reset) : %C(white)%s %C(bold green)-- %an%C(reset) %C(bold red)%d%C(reset)' --date=relative"
alias gs="git status"
alias gg="gitgraph"
